### ISSUE TITLE
error on build with v2.9 

### ISSUE THREAD

**Issue by ilyar** [Restream/reindexer#58]
```
# github.com/restream/reindexer/bindings/builtin
/usr/bin/ld: //usr/local/lib/libreindexer.a(backtrace.cc.o): in function `reindexer::debug::backtrace_internal(void**, unsigned long, void*, reindexer::string_view&)':
backtrace.cc:(.text+0x80): undefined reference to `_ULx86_64_init_local'
/usr/bin/ld: backtrace.cc:(.text+0xa4): undefined reference to `_ULx86_64_get_reg'
/usr/bin/ld: backtrace.cc:(.text+0xb5): undefined reference to `_ULx86_64_step'
/usr/bin/ld: //usr/local/lib/libreindexer.a(terminate_handler.cpp.o): in function `reindexer::terminate_handler()':
terminate_handler.cpp:(.text+0x135): undefined reference to `_Ux86_64_getcontext'
collect2: error: ld returned 1 exit status
```

**Comment by ilyar** [comment]
sample https://github.com/ilyar/reindexer-sample/actions

**Comment by olegator77** [comment]
Fixed in 2.9.1.

**Comment by Dan-Do** [comment]
I have the same issue when compiling the C binding for Crystal lang
```
/usr/bin/ld: /mnt/d/projects/services/lib/cridxerdb/ext/libreindexer.a(backtrace.cc.o): in function `reindexer::debug::backtrace_internal(void**, unsigned long, void*, std::basic_string_view<char, std::char_traits<char> >&)':
/mnt/d/projects/lib/reindexer/cpp_src/debug/backtrace.cc:114: undefined reference to `_ULx86_64_init_local'
/usr/bin/ld: /mnt/d/projects/lib/reindexer/cpp_src/debug/backtrace.cc:119: undefined reference to `_ULx86_64_get_reg'
/usr/bin/ld: /mnt/d/projects/lib/reindexer/cpp_src/debug/backtrace.cc:121: undefined reference to `_ULx86_64_step'
/usr/bin/ld: /mnt/d/projects/lib/reindexer/cpp_src/debug/backtrace.cc:110: undefined reference to `_Ux86_64_getcontext'
... many more here
```
I have built the statisc library file `libreindexer.a` successfully
Do you have any idea what I missed?

**Comment by Dan-Do** [comment]
Found the issue, I have to add the `--link-flags="-lunwind"`
